version: '3'

tasks:
  startnode:
    desc: Start the backend in developer mode with single-node mongodb
    cmds:
      - docker-compose -p databoutique_backend -f dev.single-node.docker-compose.yml up

  start:
    desc: Start the backend in developer mode with a mongodb cluster
    cmds:
      - docker-compose -p databoutique_backend -f dev.cluster.docker-compose.yml up

  end:
    desc: Stop the backend in developer mode
    cmds:
      - docker-compose -p databoutique_backend -f dev.docker-compose.yml down

  console:
    desc: Open console in (developer mode) running backend
    cmds:
      - docker exec -it databoutique_backend bash

  wire:
    desc: Generate new compile-time dependency injection file, called `wire_gen.go`, which is needed by our app
    cmds:
      - go run github.com/google/wire/cmd/wire

  clean:
    cmds:
      - go clean -cache
      - go clean -modcache

  deploy:
    desc: The following `task` will build our project's containers and push them to the public registry
    cmds:
      - docker build -f ./Dockerfile -t rodolfossp/databoutique-backend:latest --platform linux/amd64 .
      - docker tag rodolfossp/databoutique-backend:latest rodolfossp/databoutique-backend:latest
      - docker push rodolfossp/databoutique-backend:latest

  vendor:
    desc: Save all the libraries into our code repository
    cmds:
      - go mod download
      - go mod vendor

  genkey:
    desc: Generate a unique key.
    cmds:
      - openssl rand -hex 64.

  upgradelib:
    desc: Update all the golang libraries (https://stackoverflow.com/a/67202539)
    cmds:
      - go get -u ./...

  fmt:
    desc: Format the source code to be more inlined with Go standard style (https://pkg.go.dev/cmd/gofmt)
    cmds:
      - gofmt -s -w .

  lint:
    cmds:
      - golangci-lint run --verbose

  test:
    cmds:
      - go test ./...
